#pragma once

#define VIAL_KEYBOARD_UID {0xE0, 0xA6, 0xDA, 0x6F, 0x16, 0xD8, 0x83, 0x3D}

#define VIAL_UNLOCK_COMBO_ROWS { 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0 }

#define JOYSTICK_AXIS_COUNT 0
#define JOYSTICK_BUTTON_COUNT 25

